parameters:
    edgar_ez_favicon.generator: EdgarEz\FaviconBundle\Generator\Generator

services:
    edgar_ez_favicon.generator:
        class: %edgar_ez_favicon.generator%
        arguments:
            - @ezpublish.config.resolver


